#####################        网站配置信息       #####################
#nest:
#  title: ""
#  LETTER_TODAY_IP_MAX: 10
#  PAGE_NUMBER: 10
#  TIME_LOVE_YEAR: 2013
#  TIME_LOVE_MONTH: 2
#  TIME_LOVE_DAY: 10
#  SERVLET_FIRST_PAGE: "firstPage"
#  TOKEN_URL: "/admin"
#  TOKEN_PHONE: "13221066206"
#  TOKEN_DO_LOGIN: "admin"
#  TOKEN_GOOGLE_KEY: "admin123"
#
#  itpk:
#    API_KEY: "2b953da46ab18efce647ce826239b07e"
#    API_SECRET: "yddptyiwoht9"
#  turingapi:
#    API_KEY: "35eeb5ba65784de197227997449a508a"
#    API_SECRET: "b5d1f9ca90e59799"
#  #上传服务  OSS
#  ENABLE_OSS: false
#
#
#
######################################################################
# Https 配置
server:
  port: 4431
  ssl:
    key-store: classpath:yiyjm-com-0503022404.jks
    key-store-password: wx1ATFiR
    key-store-type: JKS
    #key-alias: yiyjm.com
  compression:
    enabled: true
    min-response-size: 512
  tomcat:
    max-threads: 150
  max-http-header-size: 102400
# Spring 配置
spring:
  datasource:
    username: yiyjm
    password: rain8240
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/nest?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    url: jdbc:mysql://150.109.108.7:3306/nest?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
  freemarker:
    cache: true
    settings:
      number_format: 0.######
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    port: 465
    host: smtp.ym.163.com
    username: jonny6015@163.com
    password: HLGHPKOYZCSLEEKY
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true
# MyBatis 配置
mybatis:
  type-aliases-package: com.yiyjm.nest.entity
  mapper-locations: mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false
# 日志配置
logging:
  level:
    root: info
