server:
  #端口号
  port: 7751

spring:
  datasource:
    username: lmsite
    password: rain8240
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.172.232:3306/yiyjm-nest?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
  freemarker:
    cache: true
    settings:
      number_format: 0.######
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    port: 465
    host: smtp.ym.163.com
    username: jonny6015@163.com
    password: HLGHPKOYZCSLEEKY
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
            required: true
# Https 配置
#server:
#  port: 443
#  ssl:
#    key-store: classpath:www.yiyjm.com.jks
#    key-store-password: xxxxxxxxx
#    key-store-type: JKS
#    key-alias: www.yiyjm.com
#  compression:
#    enabled: true
#    min-response-size: 512
#  tomcat:
#    max-threads: 150
#  max-http-header-size: 102400

mybatis:
  type-aliases-package: com.yiyjm.nest.entity
  #mapper-locations: mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    root: info

